vich_uploader:
    mappings:
        avis_file:
            uri_prefix: /files/enquete_publiques/avis
            upload_destination: '%kernel.project_dir%/public/files/enquete_publiques/avis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        enquete_document:
            uri_prefix: /files/enquete_publiques/documents
            upload_destination: '%kernel.project_dir%/public/files/enquete_publiques/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
